# Site settings
title: Casperlabs Blog
# email:
description: "Official Casperlabs blog"
# url: ""
# baseurl: ""
github_username:  casperlabs

theme: jekyll-theme-minimal
# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from


# configure kramdown
kramdown:
  parse_block_html: true


